[package]
name = "p0f-rs"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
chrono = "0.4"
thiserror = "1.0"

serde = { version = "1.0", optional = true }

[dev-dependencies]
eyre = "0.6"
clap = { version = "4.5", features = ["derive"] }